@searchUrl=PUT-YOUR-SEARCH-SERVICE-URL-HERE
@personalAccessToken=PUT-YOUR-PERSONAL-ACCESS-TOKEN-HERE
@api-version = 2025-09-01

### List all existing indexes by name (you should see the hotels-sample-index).
GET {{searchUrl}}/indexes?api-version={{api-version}}&$select=name  HTTP/1.1
Authorization: Bearer {{personalAccessToken}}

### Send a search query to the hotels-sample-index.
### This query is a term query that search for "walking distance to live music".
### You can compare this result against semantic ranking results in the next request.
POST {{searchUrl}}/indexes/hotels-sample-index/docs/search?api-version={{api-version}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{personalAccessToken}}

{
  "search": "walking distance to live music",
  "select": "HotelId, HotelName, Description",
  "count": true,
  "queryType": "simple"
}

### Send a search query to the hotels-sample-index with semantic ranking.
### This query also searches for "walking distance to live music".
### For this particular query and index, the effects of semantic ranking are more pronounced in the second half of the results
POST {{searchUrl}}/indexes/hotels-sample-index/docs/search?api-version={{api-version}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{personalAccessToken}}

{
  "search": "walking distance to live music",
  "select": "HotelId, HotelName, Description",
  "count": true,
  "queryType": "semantic",
  "semanticConfiguration": "semantic-config"
}

### Return captions in the query
### Captions are relevant passages from each result
### Captions can include hit highlighting
POST {{searchUrl}}/indexes/hotels-sample-index/docs/search?api-version={{api-version}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{personalAccessToken}}

{
  "search": "walking distance to live music",
  "select": "HotelId, HotelName, Description",
  "count": true,
  "queryType": "semantic",
  "semanticConfiguration": "semantic-config",
  "captions": "extractive|highlight-true"
}

### Return semantic answers in the query
### Semantic answers can be returned if the query is phrased as question
### Semantic answers are verbatim snippets from the results
### This experience works best on content provides answers to questions
### We changed the query to a question to demonstrate this feature
POST {{searchUrl}}/indexes/hotels-sample-index/docs/search?api-version={{api-version}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{personalAccessToken}}

{
  "search": "what's a good hotel for people who like to read",
  "select": "HotelId, HotelName, Description",
  "count": true,
  "queryType": "semantic",
  "semanticConfiguration": "semantic-config",
  "captions": "extractive|highlight-true",
  "answers": "extractive"
}
