@searchUrl = PUT-YOUR-SEARCH-URL-HERE
@api-version = 2025-09-01
# Token for Azure AI Search
@searchAccessToken = PUT-YOUR-SEARCH-TOKEN-HERE
# Token for Azure OpenAI (Cognitive Services)
@aoaiAccessToken = PUT-YOUR-AZURE-OPENAI-TOKEN-HERE
@aoaiUrl = PUT-YOUR-AZURE-OPENAI-URL-HERE
@aoaiGptModel = gpt-4o-mini
@aoaiGptDeployment = gpt-4o-mini
@index-name = hotels-sample-index

# Commands to get separate tokens:
# az account get-access-token --resource https://search.azure.com --query "accessToken" -o tsv
# az account get-access-token --resource https://cognitiveservices.azure.com --query "accessToken" -o tsv

### List existing indexes by name (verify the connection)
GET {{searchUrl}}/indexes?api-version={{api-version}}&$select=name HTTP/1.1
Authorization: Bearer {{searchAccessToken}}

### 1 - Get search results for a term query and save results in a variable
# @name searchResults
POST {{searchUrl}}/indexes/{{index-name}}/docs/search?api-version={{api-version}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{searchAccessToken}}

{
    "search": "Can you recommend a few hotels with views of the ocean",
    "queryType": "semantic",
    "semanticConfiguration": "semantic-config",
    "select": "Description,HotelName,Tags",
    "top": 5
}

### 2 - Use search results in Azure OpenAI call to a chat completion model
POST {{aoaiUrl}}/openai/deployments/{{aoaiGptDeployment}}/chat/completions?api-version=2024-08-01-preview HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{aoaiAccessToken}}

{
    "messages": [
        {
            "role": "system",
            "content": "You  are a friendly assistant that recommends hotels based on activities and amenities. Answer the query using only the search result. Answer in a friendly and concise manner. Answer ONLY with the facts provided. If there isn't enough information below, say you don't know."
        },
        {
            "role": "user",
            "content": "Based on the hotel search results, can you recommend hotels hotels with views of the ocean? Here are all the hotels I found: Hotel 1: {{searchResults.response.body.value[0].HotelName}} - {{searchResults.response.body.value[0].Description}}. Hotel 2: {{searchResults.response.body.value[1].HotelName}} - {{searchResults.response.body.value[1].Description}}. Hotel 3: {{searchResults.response.body.value[2].HotelName}} - {{searchResults.response.body.value[2].Description}}. Hotel 4: {{searchResults.response.body.value[3].HotelName}} - {{searchResults.response.body.value[3].Description}}. Hotel 5: {{searchResults.response.body.value[4].HotelName}} - {{searchResults.response.body.value[4].Description}}. Please recommend which hotels offer views of the ocean based on their descriptions."
        }
    ],
    "max_tokens": 1000,
    "temperature": 0.7
}
