@baseUrl = PUT-YOUR-SEARCH-SERVICE-URL-HERE
@apiKey = PUT-YOUR-SEARCH-SERVICE-ADMIN-API-KEY-HERE
@storageConnectionString = PUT-YOUR-STORAGE-CONNECTION-STRING-HERE
@blobContainer = PUT-YOUR-CONTAINER-NAME-HERE


### Create a data source (we used nasa-ebooks-small and a free search service to test this example.)
POST {{baseUrl}}/datasources?api-version=2023-11-01
Content-Type: application/json
api-key: {{apiKey}}

    {
        "name" : "nasa-entity-linking-ds",
        "description" : "First 10 PDF files out of nasa-e-book/text-only folder",
        "type" : "azureblob",
        "credentials" :
        { "connectionString" :
            "{{storageConnectionString}}"
        },
        "container" : { "name" : "{{blobContainer}}" }
    }


### Create a skillset
POST {{baseUrl}}/skillsets?api-version=2023-11-01
Content-Type: application/json
api-key: {{apiKey}}

    {
        "name": "nasa-entity-linking-ss",
        "description":"Entity Linking V3, using default values",
        "skills":[
                {
                "@odata.type": "#Microsoft.Skills.Text.V3.EntityLinkingSkill",
                "context": "/document",
                "inputs": [
                    {
                        "name": "text", 
                        "source": "/document/content"
                    }
                ],
                "outputs": [
                    {
                        "name": "entities", 
                        "targetName": "entities" 
                    }
                ]
            }
        ]
    }

### Create an index
POST {{baseUrl}}/indexes?api-version=2023-11-01
Content-Type: application/json
api-key: {{apiKey}}

    {
        "name": "nasa-entity-linking-idx",
        "fields": [
            {
            "name": "id",
            "type": "Edm.String",
            "key": true,
            "searchable": true,
            "filterable": false,
            "facetable": false,
            "sortable": true
            },
            {
            "name": "metadata_storage_name",
            "type": "Edm.String",
            "searchable": false,
            "filterable": false,
            "facetable": false,
            "sortable": false
            },
            {
            "name": "content",
            "type": "Edm.String",
            "sortable": false,
            "searchable": true,
            "filterable": false,
            "facetable": false
            },
            { 
            "name": "EntityLink", 
            "type": "Collection(Edm.ComplexType)", 
            "fields": [
                { "name": "Name", "type": "Edm.String", "filterable": true, "sortable": false, "facetable": false, "searchable": true },
                { "name": "Url", "type": "Edm.String", "searchable": true, "filterable": true, "sortable": false, "facetable": false }
            ]
            }
        ]
    }

### Create and run an indexer (takes a minute)
POST {{baseUrl}}/indexers?api-version=2023-11-01
Content-Type: application/json
api-key: {{apiKey}}

    {	
        "name" : "nasa-entity-linking-idxr",
        "dataSourceName" : "nasa-entity-linking-ds",
        "targetIndexName" : "nasa-entity-linking-idx",
        "skillsetName" : "nasa-entity-linking-ss",
        "fieldMappings" : [
            {
            "sourceFieldName" : "metadata_storage_path",
            "targetFieldName" : "id",
            "mappingFunction" :
                { "name" : "base64Encode" }
            },
            {
            "sourceFieldName" : "metadata_storage_name",
            "targetFieldName" : "metadata_storage_name",
            "mappingFunction" :
                { "name" : "base64Encode" }
            },
            {
            "sourceFieldName" : "content",
            "targetFieldName" : "content"
            }
        ],
        "outputFieldMappings" :
        [
            {
            "sourceFieldName" : "/document/entities/*",
            "targetFieldName" : "EntityLink"
            }
        ],
        "parameters":
        {
            "maxFailedItems":-1,
            "maxFailedItemsPerBatch":-1,
            "configuration":
            {
            "dataToExtract": "contentAndMetadata",
            "parsingMode": "default",
            "firstLineContainsHeaders": false,
            "delimitedTextDelimiter": ","
            }
        }
    }

### Get indexer status (watch for items processed and errors)
GET {{baseUrl}}/indexers/nasa-entity-linking-idxr/status?api-version=2023-11-01
  api-key: {{apiKey}}

### Run a search query
POST {{baseUrl}}/indexes/nasa-entity-linking-idx/docs/search?api-version=2023-11-01
  Content-Type: application/json
  api-key: {{apiKey}}

    {
        "search": "*",
        "select": "metadata_storage_name, content, EntityLink",
        "count": true
    }
